baseURL = "/"
languageCode = 'de-AT'
title = 'Psido'
subtitle= 'PatientInnenverwaltung'
theme = "hugo-serif-theme"
DefaultContentLanguage = "de"
metaDataFormat = "yaml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.alert]
    content = "Diese Seite verwendet keine Cookies, weil wir 100% Wert auf Privatsphäre legen."
    show = true

  [params.moreinfo]
    content = "Psido wurde für eine Psychologin in freier Praxis programmiert um ihre PatientInnenverwaltung zu vereinfachen. Die Zielgruppe von Psido beeinhaltet selbständige Menschen in Gesundheitsberufen die eine einfache, schlanke PatientInnenverwaltung und automatische Rechnungslegung brauchen. Psido hilft Ihnen beim Helfen und spart Ihnen Zeit damit Sie sich auf die Arbeit mit Menschen konzentrieren können."
    show = true

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    # primary = "#f24088"
    primary = "#4050B5"
    black = "#2f2f41"
    white = "#ffffff"
    # white_offset = "#f6f7ff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    #meta_twitter_site = "@zerostaticio"
    #meta_twitter_creator = "@zerostaticio"
    #meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Wolfgang Hennerbichler, A-4225 Luftenberg'


[menu]
  # Main Menu
  [[menu.main]]
    name = "Funktionen"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "Preis"
    url = "/price/"
    weight = 2

  [[menu.main]]
    name = "Über uns"
    url = "/team/"
    weight = 3

  [[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 4
    
  [[menu.main]]
    name = "Anmelden"
    url = "https://do.psido.at"
    weight = 5
    [menu.main.params]
        class = "btn btn-light"

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Kontakt"
    url = "/contact/"
    weight = 2

  [[menu.footer]]
    name = "Anmelden"
    url = "https://do.psido.at"
    weight = 3
